SnapCookRecipe/recipegeneration/__init__.py
from flask import Flask
from flask_login import LoginManager
from .model import db, init_app

def create_app():
    app = Flask(__name__, template_folder='Templates')

    app.config['SECRET_KEY'] = 'secret-key-goes-here'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.foodsqlite'
    

    init_app(app)  # Use the modified init_app function

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .model import User

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    # Import routes and blueprints
    from .routes import routes as main_blueprint
    from .auth import auth as auth_blueprint
    from .food import food_blueprint
    from .recommend import recommend_blueprint
    from .nutrients import nutrients_blueprint
    from .grocery import grocery_blueprint
    from .mealplan import mealplan_blueprint

    # Register blueprints
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(food_blueprint)
    app.register_blueprint(recommend_blueprint)
    app.register_blueprint(nutrients_blueprint)
    app.register_blueprint(grocery_blueprint)
    app.register_blueprint(mealplan_blueprint)

    return app

SnapCookRecipe/recipegeneration/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from .model import db, User
from flask_login import login_user, login_required, logout_user

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    # login code goes here
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('routes.profile'))

@auth.route('/signup')
def signup():
    return render_template('signup.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    # code to validate and add user to database goes here
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    user = User.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database

    if user: # if a user is found, we want to redirect back to signup page so user can try again
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    # create a new user with the form data. Hash the password so the plaintext version isn't saved.
    new_user = User(email=email, name=name, password=generate_password_hash(password, 'pbkdf2:sha256'))

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

SnapCookRecipe/recipegeneration/routes.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

# Import db from models.py
from .model import db

#food imports
from flask import Blueprint, render_template, redirect, request, session, abort, jsonify

from recipegeneration.output import output
from flask_sqlalchemy import SQLAlchemy
import bcrypt
import os
import json
import requests  # Add this import

routes = Blueprint('routes', __name__)

@routes.route('/',methods=['GET'])
@login_required
def home():
    return render_template('home.html')

@routes.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.name)


#about page
@routes.route('/about',methods=['GET'])
@login_required
def about():
    return render_template('about.html')

SnapCookRecipe/recipegeneration/templates/about.html
{% extends "layout.html" %}
{% block content %}



        </div>
    </div>
</div>    

<div id="section-about"onload="sampleFunction()">
    <div id="aboutcard" class="card col-md-8">
        <div class="card-header ">
          <b>ABOUT</b>
        </div>
        <div class="card-body">
          <p class="title">TITLE : Recipe Generation From Food Image</p>
          <p class="title">ABSTRACT :</p>
          <p class="aboutcontent">People enjoy food photography because they appreciate
            food. Behind each meal there is a story described in a complex recipe and, unfortunately, by simply looking at a food
            image we do not have access to its preparation process.
            Therefore, in this paper we introduce an inverse cooking
            system that recreates cooking recipes given food images.
            Our system predicts ingredients as sets by means of a novel
            architecture, modeling their dependencies without imposing any order, and then generates cooking instructions by
            attending to both image and its inferred ingredients simultaneously.
            </p>
        </div>
      </div>
</div>

{% endblock content %}

SnapCookRecipe/recipegeneration/templates/add.html
{% extends "layout.html" %}
{% block content %}


<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>MEAL TRACKER | Add Food Item</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="./bs/css/united.min.css" />
		<link rel="stylesheet" href="./styles.css" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

        <style>
			.custom-center {
				display: flex;
				justify-content: center;
			}
			
		</style>
		<!-- Increase the width of columns -->
<style>
    .col-lg-4, .col-lg-8 {
        width: 80%; /* Adjust the width as needed */
    }

    /* You can adjust other column sizes (.col-lg-*) similarly */
</style>

<!-- Increase the spacing between columns -->
<style>
    .row {
        margin-left: -15px; /* Adjust the negative margin as needed */
        margin-right: -15px; /* Adjust the negative margin as needed */
    }

    .col-lg-4, .col-lg-8 {
        padding-left: 15px; /* Adjust the padding as needed */
        padding-right: 15px; /* Adjust the padding as needed */
    }
</style>
<!-- Increase font size for all text content -->
<style>
    body {
        font-size: 16px; /* You can adjust the value as needed */
    }
</style>

<!-- Increase font size for headings -->
<style>
    h1, h2, h3, h4, h5, h6 {
        font-size: 24px; /* You can adjust the value as needed */
    }
</style>

<!-- Increase font size for specific elements -->
<style>
    .form-control {
        font-size: 18px; /* You can adjust the value as needed */
    }
    .btn {
        font-size: 18px; /* You can adjust the value as needed */
    }
</style>

	</head>
	<body>

		<div class="container-fluid custom-center " id="wrapper">
			<div class="row justify-content-center mt-5" style="margin-left: 150px;">
			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
				<!--	<h1>
						<a href="{{ url_for('mealplan_blueprint.index')}}">MEAL PLANNER</a>
					</h1> -->
					
					<div class="row t20 ">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
							  <li role="presentation">
							  	<a href="{{ url_for('mealplan_blueprint.index')}}" title="Home" class="btn btn-secondary btn-lg mb-3">Home</a>
							  </li>
							<!--  <li role="presentation" class="active">
							  	<a href="{{ url_for('mealplan_blueprint.add')}}" title="Add Food Item">Add Food Item</a>
							  </li> --> 
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t30" >
				<div class="col-lg-8 col-lg-offset-2">
					<div class="card" style="border: 4px solid #d3d3d3;  box-shadow: 5px 5px 15px rgba(0, 0, 2, 0.4);">
                        <div class="card-body">
                            <h3 class="card-title">
								<i class="glyphicon glyphicon-plus-sign"></i> MEAL TRACKER
							</h3>
							<hr />

							<form action="{{ url_for('mealplan_blueprint.add')}}" method="POST" role="form">
							
								<div class="row">
									<div class="col-lg-4">
										<div class="form-group">
											<label for="food-name">Food Name</label>
						                  	<input type="text" class="form-control" id="food-name" name="food-name" placeholder="Food Name" value="{{ food.name }}" autofocus>
										</div>
							
									</div>
									<div class="col-lg-4">
										<div class="form-group">
						                  <label for="protein">Protein</label>
						                  <input type="number" class="form-control" id="protein" name="protein"  value="{{ food.proteins }}" placeholder="Protein">
						                </div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
						                  <label for="carbohydrates">Carbohydrates</label>
						                  <input type="number" class="form-control" id="carbohydrates" name="carbohydrates"  value="{{ food.carbs }}"  placeholder="Carbohydrates">
						                </div>
									</div>
								</div>

								<div class="row">
									<div class="col-lg-4">
										<div class="form-group">
						                  <label for="fat">Fat</label>
						                  <input type="number" class="form-control" id="fat" name="fat"  value="{{ food.fats }}"  placeholder="Fat">
						                </div>
									</div>

									<div class="col-lg-4 mt-3 ml-5">
										<div class="form-group">
											<label style="visibility:hidden">submit</label>
                                            <input type="hidden" name="food-id" value="{{ food.id }}">
											<button type="submit" class="btn btn-primary btn-block">
												<i class="glyphicon glyphicon-upload"></i> Submit
											</button>
										</div>
									</div>
								</div>
							
							</form>	
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-8 col-lg-offset-2 ml-3 mt-3">
					<div class="panel panel-default rounded" style="border: 4px solid #d3d3d3; box-shadow: 5px 5px 15px rgba(0, 0, 2, 0.4);"> <!-- Add glowing border effect -->
						<div class="panel-body">
							<h4 class="lean-h text-black mt-4">
								<i class="glyphicon glyphicon-th-list"></i> Food Items
							</h4>
						</div>
						<div class="table-responsive">
							<table class="table table-striped table-hover table-bordered">
								<thead>
									<tr>
										<th style="width: 5%;">No.</th>
										<th>Name</th>
										
										<th style="width: 10%;">Protein</th>
										<th style="width: 16%;">Carbohydrates</th>
										<th style="width: 10%;">Fat</th>
										<th style="width: 12%;">Calories</th>
										<th style="width: 20%;">Actions</th>
									</tr>
								</thead>
								<tbody>
                                    {% for food in foods %}
									<tr>
										<td>{{ food.id }}</td><td>{{ food.name }}</td><td>{{ food.proteins }}</td>
										<td>{{ food.carbs }}</td><td>{{ food.fats }}</th><td>{{ food.calories }}</td>
										<td>
											<a href="{{ url_for('mealplan_blueprint.edit_food', food_id=food.id) }}" class="btn btn-success btn-xs">
												<i class="glyphicon glyphicon-pencil"></i> Edit
											</a> 
											<a href="{{ url_for('mealplan_blueprint.delete_food', food_id=food.id) }}" class="btn btn-danger btn-xs">
                                                <i class="glyphicon glyphicon-trash"></i> Delete
                                            </a>
                                             
										</td>
									</tr>
                                    {% endfor %}
							
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

		<!--<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						
					</div>
				</div>
			</footer> -->	

		</div>
    </div>
		<!-- jQuery -->
		<script src="./bs/js/jquery.min.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="./bs/js/bootstrap.min.js"></script>
	</body>
</html>

{% endblock %}

SnapCookRecipe/recipegeneration/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no">

    <!-- CSS -->
    <!-- Comment out the Bootstrap CSS link -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    
    <!-- Add Bootswatch Flatly theme link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/flatly/bootstrap.min.css">
    
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <title>SNAPCOOK</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/cheflogo.png') }}">
</head>
<body>
    
    <!-- Navigation Bar 
    <div id="Section-1">
        <nav class="navbar navbar-expand-lg bg-primary">
            <a class="navbar-brand mr-auto" href="{{url_for('routes.home')}}" style="font-family: 'Times New Roman', Times, serif;">
                <img src="{{ url_for('static',filename='images/cute-chef.jpg') }}" width="30" height="30" class="d-inline-block align-top" alt="" style="margin-top: -5.5px;">
                SNAPCOOK</a>
            <a href="{{url_for('routes.home')}}" class="w-100 text-center text-dark">RECIPE GENERATION FROM FOOD IMAGE</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                <a class="nav-link" href="{{url_for('routes.home')}}" onclick="console.log('Clicked on Home')">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                <a class="nav-link" href="{{url_for('routes.about')}}" onclick="console.log('Clicked on About')">About</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('routes.profile') }}" onclick="console.log('Clicked on Profile')">
                        Profile
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text-light" href="{{ url_for('grocery_blueprint.grocery') }}">Grocery Items</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('recommend_blueprint.recipe_recommend') }}" onclick="console.log('Clicked on Recommendation')">
                        Recommendation
                    </a>
                </li>
              <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('mealplan_blueprint.index') }}" onclick="console.log('Clicked on MealPlan Index')">
                        Meal Plan
                    </a>
                </li> 
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('mealplan_blueprint.add') }}" onclick="console.log('Clicked on MealPlan Add')">
                        Meal Plan Add
                    </a>
                </li>

                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('nutrients_blueprint.nutrients_value') }}" onclick="console.log('Clicked on Nutrients')">
                        Nutrients
                    </a>
                </li> 
                <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('auth.logout')}}" onclick="console.log('Clicked on Logout')">Logout</a>
                </li>
            </ul>
            </div>
        </nav>
    </div> -->

    {% block content %}{% endblock %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="{{ url_for('static', filename='main.js') }}" type="text/javascript"></script>
</body>
</html>

SnapCookRecipe/recipegeneration/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit=no">

    <!-- CSS -->
    <!-- Comment out the Bootstrap CSS link -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    
    <!-- Add Bootswatch Flatly theme link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.1.3/dist/flatly/bootstrap.min.css">
    
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <title>SNAPCOOK</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/cute-chef.jpg') }}">
</head>
<body>
    
    <!-- Navigation Bar -->
    <div id="Section-1">
        <nav class="navbar navbar-expand-lg bg-primary">
            <a class="navbar-brand mr-auto" href="{{url_for('routes.home')}}" style="font-family: 'Times New Roman', Times, serif;">
                <img src="{{ url_for('static',filename='images/cute-chef.jpg') }}" width="30" height="30" class="d-inline-block align-top" alt="" style="margin-top: -5.5px;">
                SNAPCOOK</a>
            <a href="{{url_for('routes.home')}}" class="w-100 text-center text-dark">RECIPE GENERATION FROM FOOD IMAGE</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                <a class="nav-link" href="{{url_for('routes.home')}}" onclick="console.log('Clicked on Home')">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                <a class="nav-link" href="{{url_for('routes.about')}}" onclick="console.log('Clicked on About')">About</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('routes.profile') }}" onclick="console.log('Clicked on Profile')">
                        Profile
                    </a>
                </li>
             <!--  <li class="nav-item active">
                    <a class="nav-link text-light" href="{{ url_for('grocery_blueprint.grocery') }}">Grocery Items</a>
                </li> --> 
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('recommend_blueprint.recipe_recommend') }}" onclick="console.log('Clicked on Recommendation')">
                        Ingredient-based-Recommendation
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('mealplan_blueprint.add') }}" onclick="console.log('Clicked on MealPlan Add')">
                        Meal Tracker
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('auth.logout')}}" onclick="console.log('Clicked on Logout')">Logout</a>
                </li>
            </ul>
            </div>
        </nav>
    </div>

    {% block content %}{% endblock %}

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="{{ url_for('static', filename='main.js') }}" type="text/javascript"></script>
</body>
</html>

SnapCookRecipe/recipegeneration/templates/home.html
{% extends "layout.html" %}
{% block home %}
<div id="info" class="col-md-8">
    <div class="card m-3">
        <!-- Display the image if img is not None -->
        {% if img %}
        <img src="{{ url_for('static', filename=img) }}" class="card-img-top" alt="Food Image">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title text-center" id="infotitle">Generate recipe from a food image</h5>
            <br>
            <p class="card-text" id="infobody">A recipe along with title, ingredient and instructions will be shown here</p>
            <p class="card-text"><small class="text-muted">Will take a few seconds to process! <br>45s approx</small></p>
        </div>
    </div>
</div>
<div id="loading" style="display:none;" class="col-md-8">
    <div class="loader">
        <div class="inner one"></div>
        <div class="inner two"></div>
        <div class="inner three"></div>
        <!--<h4>Loading</h4> -->
    </div>
</div>
{% endblock %}

SnapCookRecipe/recipegeneration/templates/index.html
{% extends "header.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>MEAL TRACKER | Home</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="./bs/css/united.min.css" />
		<link rel="stylesheet" href="./styles.css" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">
			
			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{ url_for('mealplan_blueprint.index')}}">MEAL TRACKER</a>
					</h1>
					
					<div class="row t20">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
								<li role="presentation">
									<a href="{{ url_for('mealplan_blueprint.add') }}" title="Add Food Item" class="btn btn-secondary btn-lg mb-3">Add Food Item</a>
								</li>
								<br/>
							<!--<li role="presentation">
									<a href="{{ url_for('mealplan_blueprint.view', log_id=log.id) }}" title="View Food Items">View Food Items</a>

								</li> -->
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-4 col-lg-offset-4">
					<div class="panel panel-default">
						<div class="panel-body">
							<form action="{{ url_for('mealplan_blueprint.create_log')}}" method="POST" role="form">
								<div class="form-group">
									<label><i class="glyphicon glyphicon-plus-sign"></i> Add New Date</label>
									<div class="input-group">
										<input type="date" class="form-control" name="date" placeholder="Select New Date" aria-label="date" aria-describedby="add-btn">
										<span class="input-group-btn">
											<button type="submit" class="btn btn-primary" id="add-btn">
												<i class="glyphicon glyphicon-plus-sign"></i> Add Date
											</button>
										</span>
									</div>
								</div>
							</form>	
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-12">
					<h4 class="text-center text-white"><strong>Existing Records ({{ log_dates|length }})</strong></h4>
				</div>
			</div>

			{% for row in log_dates|batch(4) %}
			<div class="row t20">
				{% for log_date in row %}
				<div class="col-lg-3">
					<div class="panel panel-warning">
						<div class="panel-body text-bold">
							<i class="glyphicon glyphicon-calendar"></i> {{ log_date['log_date'].date.strftime('%B %d, %Y') }}

							<a class="btn btn-primary btn-xs pull-right" href="{{ url_for('mealplan_blueprint.view', log_id=log_date['log_date'].id) }}">
								View <i class="glyphicon glyphicon-arrow-right"></i>
							</a>.
						</div>
						<ul class="list-group">
							<li class="list-group-item text-bold"><span class="badge">{{ log_date['proteins'] }}</span> Protein</li>
							<li class="list-group-item text-bold"><span class="badge">{{ log_date['carbs'] }}</span> Carbohydrate</li>
							<li class="list-group-item text-bold"><span class="badge">{{ log_date['fats'] }}</span> Fat</li>
							<li class="list-group-item text-bold"><span class="badge">{{ log_date['calories'] }}</span> Calories</li>
						</ul>
					</div>
				</div>
				{% endfor %}
			</div>
			{% endfor %}
			</div>

		</div>

		<!-- jQuery -->
		<script src="./bs/js/jquery.min.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="./bs/js/bootstrap.min.js"></script>
	</body>
</html>
{% endblock %}

SnapCookRecipe/recipegeneration/templates/profile.html
{% extends "header.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ name }}!
</h1>
{% endblock %}